"""taiyi_core_session.invariant — companion subpackage exposing the public API contract.

This subpackage re-exports the public surface of :mod:`taiyi_core_session`
so other packages in the taiyi workspace can declare a stable dependency
on the contract without coupling to the implementation layout.

1:1 with upstream `packages/core/session/src/invariant.ts` (a barrel).
"""

from __future__ import annotations

from taiyi_core_session.session import (  # noqa: F401
    ATTACHMENTS,
    Session,
    SessionEntry,
    SessionForkError,
    SessionForkErrorCode,
    SessionForkSource,
    SessionStore,
    SessionSurface,
    SurfaceFoldReplacement,
    SurfaceFoldResult,
    SurfaceManager,
    adopt_session_event,
    canonical_header,
    collect_session_callbacks,
    deep_freeze,
    derive_event_message,
    fold_request_header,
    fold_surface,
    freeze_restored_object,
    has_provider_model,
    header_equals,
    is_append_surface_event,
    is_replacement_surface_event,
    is_surface_event,
    snapshot_json_value,
    snapshot_session_event,
    snapshot_session_header,
    validate_restored_session_header,
    validate_session_header,
)
from taiyi_core_session.surface import (
    ReplaceOpDict,
    SurfaceEventType,
    SurfaceIntent,
    SurfaceOp,
    is_surface_eligible_type,
    is_surface_op_append,
    is_surface_op_replace,
    make_replace_op,
)
from taiyi_core_session.turn import (
    SESSION_FORMAT_VERSION,
    AgentCancelCause,
    TurnEndAborted,
    TurnEndBlocked,
    TurnEndCancelCause,
    TurnEndCompleted,
    TurnEndError,
    TurnEndInterrupted,
    TurnEndMaxTokens,
    TurnEndReason,
)
from taiyi_core_session.types import (
    KNOWN_SESSION_EVENT_TYPES,
    CreateSessionMeta,
    CreateSessionOptions,
    EpochHeader,
    JsonValue,
    PrepareSessionOptions,
    RequestContext,
    RequestHeaderReason,
    RestoredSessionOptions,
    SessionEvent,
    SessionEventMap,
    SessionEventType,
    SessionHeader,
    SessionId,
    TodoItem,
    is_json_value,
    make_session_id,
)

__all__ = [
    # types
    "JsonValue",
    "is_json_value",
    "SessionId",
    "make_session_id",
    "SessionHeader",
    "CreateSessionMeta",
    "CreateSessionOptions",
    "RestoredSessionOptions",
    "PrepareSessionOptions",
    "TodoItem",
    "EpochHeader",
    "RequestContext",
    "RequestHeaderReason",
    "SessionEventMap",
    "SessionEventType",
    "KNOWN_SESSION_EVENT_TYPES",
    "SessionEvent",
    # surface types
    "SurfaceOp",
    "SurfaceEventType",
    "SurfaceIntent",
    "ReplaceOpDict",
    "is_surface_eligible_type",
    "is_surface_op_append",
    "is_surface_op_replace",
    "make_replace_op",
    # turn
    "SESSION_FORMAT_VERSION",
    "AgentCancelCause",
    "TurnEndCancelCause",
    "TurnEndCompleted",
    "TurnEndAborted",
    "TurnEndBlocked",
    "TurnEndError",
    "TurnEndMaxTokens",
    "TurnEndInterrupted",
    "TurnEndReason",
    # session runtime
    "snapshot_json_value",
    "deep_freeze",
    "freeze_restored_object",
    "adopt_session_event",
    "snapshot_session_event",
    "validate_session_header",
    "validate_restored_session_header",
    "snapshot_session_header",
    "has_provider_model",
    "is_surface_event",
    "is_append_surface_event",
    "is_replacement_surface_event",
    "derive_event_message",
    "SurfaceFoldReplacement",
    "SurfaceFoldResult",
    "SessionSurface",
    "fold_surface",
    "SurfaceManager",
    "canonical_header",
    "header_equals",
    "fold_request_header",
    "collect_session_callbacks",
    # store
    "ATTACHMENTS",
    "SessionEntry",
    "SessionForkSource",
    "SessionForkErrorCode",
    "SessionForkError",
    "SessionStore",
    "Session",
]
